### ISSUE TITLE
Fix the plot

### ISSUE THREAD

**Issue by Kenkleinman** [katieleap/odds-tool#2]
I made it display.  

Now, fix the axis labels, and (harder) get rid of the discontinuities.  This thing is easier to work with if you pull it out of the server.R and just open in a plain R function/file.  It doesn't actually have anything reactive in it, right now.

**Comment by katieleap** [comment]
The baseline probability ranges from 0.1 to 0.9, so I made those the limits of the graph (somehow there are multiple entries for 0.001, hence the bar of green). If we want it to be continuous 0-1, we'd have to change the original sequence.
