### ISSUE TITLE
Baseline probability input

### ISSUE THREAD

**Issue by katieleap** [katieleap/odds-tool#5]
Next to the graph or as part of the sidebar?

**Comment by Kenkleinman** [comment]
I think above the table, or next to it?  There will also need to be some
text, explaining that this is the probability of the disease overall, in
the population, maybe giving an example.  It would be nice to have an
example where the baseline probability is large, and use that as the
default filling in the table with numbers that match.

---

---

Ken Kleinman, ScD
Associate Professor, Department of Biostatistics and Epidemiology
School of Public Health and Health Sciences
University of Massachusetts, Amherst

Lecturer, Department of Population Medicine
Harvard Medical School

My blog on SAS and R: http://sas-and-r.blogspot.com
My professional web home: http://www.kenkleinman.net/home/
My cites on Google Scholar: http://tinyurl.com/KenK-cites

---

*\* Electronic Mail is not secure, may not be read every day, and should not
be used for urgent or sensitive issues. **
